name: HashiCorp Packer
on: [push]
on: [pull]    

jobs:
  build:
    name: Packer Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Shreya Singh"
